name: Go mod check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  go-mod-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Run Go Mod Check Action
        uses: Shoothzj/go-mod-check-action@main
        with:
          prohibitIndirectDepUpdate: 'true'
